###GET RIDER COORDINATES
GET http://localhost:3001/rider-coordinator/694247dedbac381987688df1

###POST RIDER COORDINATES
POST http://localhost:3001/rider-coordinator
Content-Type: application/json

 {
    "lan":62353,
    "lat":123,
    "ride":"shakti"
 }
